name = "conda_smart_channel_alias"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]

MIRROR_SITE="https://mirrors.tuna.tsinghua.edu.cn/anaconda"
MIRRORED_PKGS_CHANNEL="""main
r
msys2
"""
MIRRORED_CLOUD_CHANNEL="""conda-forge
msys2
bioconda
menpo
pytorch
pytorch-lts
simpleitk
"""

[build]
command = "cargo install -q worker-build --version 0.0.8 && worker-build --release"
