name = "" # todo
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
SELF_URL="https://conda-mirror.example.com/"
MIRROR_SITE="https://mirrors.tuna.tsinghua.edu.cn/anaconda/"
MIRRORED_PKGS_CHANNEL="""main
r
msys2
"""
MIRRORED_CLOUD_CHANNEL="""conda-forge
msys2
bioconda
menpo
pytorch
pytorch-lts
simpleitk
"""

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
